apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  tag: 1.6.8-distroless
  addonComponents:
    grafana:
      enabled: true
    tracing:
      enabled: true
    kiali:
      enabled: true
    prometheus:
      enabled: true
  components:
    base:
      enabled: true
    cni:
      enabled: true
      tag: 1.6.8
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
        overlays:
        - apiVersion: v1
          kind: Service
          name: istio-ingressgateway
          patches:
          - path: spec.ports
            value:
            - name: status-port
              port: 15021
              targetPort: 15021
            - name: http2
              port: 80
              targetPort: 80
            - name: https
              port: 443
              targetPort: 443
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: "JSON"
  values:
    global:
      controlPlaneSecurityEnabled: true
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
       - kube-node-lease
       - kube-public
    gateways:
      istio-ingressgateway:
        sds:
          enabled: true
    pilot:
      traceSampling: 10.0
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
