alloy:
  configMap:
    create: false
    name: alloy-config
    key: config.alloy
  envFrom:
    - secretRef:
        name: alloy-azure-config
  extraEnv:
    - name: CLUSTER
      value: k8s
    - name: REGEX_METRICS_FILTER
      value: ".+"
