# Custom config
log syslog informational
log file /var/log/frr/bgpd.log informational
log timestamp precision 6
!

# Send Cilium pod/service routes
ip prefix-list CILIUM_ROUTES permit 100.64.0.0/10 le 32
!
# Accept Azure VNet routes
ip prefix-list AZURE_ROUTES permit 10.10.0.0/16 le 32
!

# Required to prevent FRR from overriding next-hop for RR clients
route-map SET_NEXTHOP permit 10
 set ip next-hop unchanged
!

router bgp 65000
 bgp router-id 10.10.17.4
 bgp log-neighbor-changes

 neighbor CILIUM_NODES peer-group
 neighbor CILIUM_NODES remote-as 65000
 neighbor CILIUM_NODES description cilium-agents
 # Dynamic peering with Cilium Agents
 bgp listen range 10.10.0.0/20 peer-group CILIUM_NODES

 # Static peering with Azure Route Server
 neighbor 10.10.16.4 remote-as 65515
 neighbor 10.10.16.4 description Azure-RouteServer-1
 neighbor 10.10.16.5 remote-as 65515
 neighbor 10.10.16.5 description Azure-RouteServer-2

 address-family ipv4 unicast
  # Cilium nodes as RR clients
  neighbor CILIUM_NODES route-reflector-client
  neighbor CILIUM_NODES soft-reconfiguration inbound

  # Announce Cilium routes to Azure Route Server
  neighbor 10.10.16.4 prefix-list CILIUM_ROUTES out
  neighbor 10.10.16.5 prefix-list CILIUM_ROUTES out

  # Required to prevent FRR from overriding next-hop for RR clients
  neighbor 10.10.16.4 route-map SET_NEXTHOP out
  neighbor 10.10.16.5 route-map SET_NEXTHOP out

  # Accept Azure routes from Azure Route Server
  neighbor 10.10.16.4 prefix-list AZURE_ROUTES in
  neighbor 10.10.16.5 prefix-list AZURE_ROUTES in
 exit-address-family
!
end
