apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempsensor
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: tempsensor
  minReadySeconds: 5
  template:
    metadata:
      name: tempsensor
      labels:
        app: tempsensor
      annotations:
        isEdgeDeployment: "true"
        targetCondition: "tags.location.building='mobile' AND tags.environment='test'"
        priority: "15"
        loggingOptions: ""
    spec:
      containers:
      - name: tempsensor
        image: mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
      nodeSelector:
        type: virtual-kubelet
      tolerations:
      - key: azure.com/iotedge
        effect: NoSchedule
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgeagent
data:
  desiredProperties: |
    {
      "systemModules": {
        "edgeHub": {
          "env": {
            "OptimizeForPerformance": {
              "value": "false"
            }
          }
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgehub
data:
  desiredProperties: |
    {
      "routes": {
        "route": "FROM /* INTO $upstream",
      },
      "storeAndForwardConfiguration": {
        "timeToLiveSecs": 7200
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempsensor
data:
  status: running
  restartPolicy: always
  version: "1.0"
  createOptions: |
    {}
